set nocompatible
set encoding=utf-8
set wrap
set mouse=a
set expandtab
set tabstop=2
set shiftwidth=2
set listchars=tab:\¦\
set list
set foldmethod=syntax
set foldnestmax=1
set foldlevelstart=3
set number
set ignorecase
set hlsearch
set nobackup
set nowb
set noswapfile
set synmaxcol=3000
set lazyredraw

syntax on

if has('win32')
  set clipboard=unnamed
else
  set clipboard=unnamedplus
endif

set termguicolors
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_nr_show = 1

autocmd BufEnter NERD_tree_* | execute 'normal R'
set guifont=Consolas:h14

map <C-n> :NERDTreeToggle<CR>

command! -nargs=1 VV rightbelow vsplit <args>
command! -nargs=1 SS rightbelow split <args>
command! Vterm rightbelow vertical terminal
command! Sterm rightbelow terminal

set runtimepath^=~/.vim
source ~/.config/vim/.vimrc.plug
