# Background
background #031219
background_opacity 0.95

# Font
font_family BlexMonoNerdFont
font_size 13

# Cursor
cursor_shape block
cursor_blink_interval 500

# macOS
macos_option_as_alt left

# Unbind Alt keys
map alt+left no_op
map alt+right no_op
